version: 2.1
jobs:
  build:
    docker:
      - image: cirrusci/flutter@3.3.10
    steps:
      - checkout
      - run: flutter doctor
      - run: flutter test 
      - run: flutter -v build apk

workflows:
  build-lint:
    jobs:
      - build
