version: 2.1
orbs:
  android: circleci/android@1.0.3
  flutter: circleci/flutter@2.0.0
jobs:
  bundle:
    executor:
      name: android/android-machine
    steps:
      - flutter/install_sdk_and_pub:
          version: 3.3.10
      - flutter/install_android_gradle_dependencies
      - flutter/install_android_gem
      - run:
          command: bundle exec fastlane distribute
          working_directory: ios
  lint:
    executor:
      name: android/android-machine
    steps:
      - flutter/install_sdk_and_pub:
          version: 3.3.10
      - flutter/install_android_gradle_dependencies
      - flutter/install_android_gem
      - run:
          command: lint
          working_directory: ios
workflows:
  distribute:
    jobs:
      - bundle
      - lint
